## Working with Json Data

In [1]:
import pandas as pd

In [2]:
df = pd.read_json("../DATASET/Recipes.json")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, Contient to serves
Columns: 3763 entries, 0 to 3762
dtypes: object(3763)
memory usage: 411.7+ KB

In [4]:
df.shape

(14, 3763)

In [5]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,3753,3754,3755,3756,3757,3758,3759,3760,3761,3762
Contient,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,...,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa
Country_State,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
cuisine,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,...,Montana,Montana,Montana,Montana,Montana,Montana,Montana,Montana,Montana,Montana
title,Ground Beef and Cabbage,Old Fashioned Peach Cobbler,St. Louis Toasted Ravioli,Amish Friendship Bread Starter,Simple Fried Morel Mushrooms,Big Al's K.C. Bar-B-Q Sauce,Lemon Zucchini Bread,Springfield Style Cashew Chicken I,Kansas City Ice Water,St. Louis Pork Steaks,...,The Humble Shepherd,Easy Slow Cooker Venison Stew,Fennel in Wine and Honey,Spinach and Goat Cheese Salad with Beetroot Vi...,Montana Russian Black Bread,Cracked Black Venison,Montana Spicy Bison Dip,Grandpa Mack's Fifth-Generation Pancake Recipe,Couscous with Dried Cherries,Jo's Mountain Mush
URL,https://www.allrecipes.com/recipe/229324/groun...,https://www.allrecipes.com/recipe/19897/old-fa...,https://www.allrecipes.com/recipe/16907/st-lou...,https://www.allrecipes.com/recipe/7063/amish-f...,https://www.allrecipes.com/recipe/220833/simpl...,https://www.allrecipes.com/recipe/44491/big-al...,https://www.allrecipes.com/recipe/58817/lemon-...,https://www.allrecipes.com/recipe/9009/springf...,https://www.allrecipes.com/recipe/51923/kansas...,https://www.allrecipes.com/recipe/73669/st-lou...,...,https://www.allrecipes.com/recipe/76519/the-hu...,https://www.allrecipes.com/recipe/32081/easy-s...,https://www.allrecipes.com/recipe/95546/fennel...,https://www.allrecipes.com/recipe/46492/spinac...,https://www.allrecipes.com/recipe/236547/monta...,https://www.allrecipes.com/recipe/18774/cracke...,https://www.allrecipes.com/recipe/256810/monta...,https://www.allrecipes.com/recipe/279565/grand...,https://www.allrecipes.com/recipe/18273/cousco...,https://www.allrecipes.com/recipe/21272/jos-mo...

In [6]:
df=df.transpose()

In [7]:
df.head()

,Contient,Country_State,cuisine,title,URL,rating,total_time,prep_time,cook_time,description,ingredients,instructions,nutrients,serves
0,Africa,None,Missouri,Ground Beef and Cabbage,https://www.allrecipes.com/recipe/229324/groun...,4.5,60,15,45,This ground beef and cabbage recipe combines l...,"[1 large head cabbage, finely chopped, 1 (14.5...","[Place cabbage, tomatoes with juice, onion, It...","{'calories': '228 kcal', 'carbohydrateContent'...",6 servings
1,Africa,None,Missouri,Old Fashioned Peach Cobbler,https://www.allrecipes.com/recipe/19897/old-fa...,4.6,130,30,70,This old-fashioned peach cobbler recipe featur...,"[2.5 cups all-purpose flour, 4 tablespoons whi...","[Make crust: Sift together flour, 3 tablespoon...","{'calories': '338 kcal', 'carbohydrateContent'...",18 servings
2,Africa,None,Missouri,St. Louis Toasted Ravioli,https://www.allrecipes.com/recipe/16907/st-lou...,4.5,25,15,10,Toasted ravioli traces its roots to St. Louis....,"[1 (16 ounce) jar marinara sauce, 1 large egg,...",[Heat marinara sauce in a saucepan over medium...,"{'calories': '374 kcal', 'carbohydrateContent'...",6 servings
3,Africa,None,Missouri,Amish Friendship Bread Starter,https://www.allrecipes.com/recipe/7063/amish-f...,4.7,14440,30,None,Amish friendship bread starter is made with ye...,"[1 (.25 ounce) package active dry yeast, 0.25 ...",[Dissolve yeast in warm water in a small bowl;...,"{'calories': '34 kcal', 'carbohydrateContent':...",120 servings
4,Africa,None,Missouri,Simple Fried Morel Mushrooms,https://www.allrecipes.com/recipe/220833/simpl...,4.7,30,20,10,"The rich, meaty flavor of fresh morel mushroom...",[1 pound fresh morel mushrooms - dirt gently b...,[Place halved morel mushrooms in a large bowl;...,"{'calories': '185 kcal', 'carbohydrateContent'...",4 servings

In [8]:
df.columns

Index(['Contient', 'Country_State', 'cuisine', 'title', 'URL', 'rating',
       'total_time', 'prep_time', 'cook_time', 'description', 'ingredients',
       'instructions', 'nutrients', 'serves'],
      dtype='object')

In [9]:
dfs = pd.read_json(' https://api.exchangerate-api.com/v4/latest/INR ')

In [10]:
dfs.head(3)

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-07,1791331202,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-07,1791331202,0.0381
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-07,1791331202,0.6700

## Working with SQL Data

In [11]:
import sys

print(sys.executable)

c:\Users\RADHE\AppData\Local\Programs\Python\Python311\python.exe

In [12]:
import sys

!{sys.executable} -m pip install --upgrade mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\radhe\appdata\local\programs\python\python311\lib\site-packages (26.7.0)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
import mysql.connector

print(mysql.connector.__version__)

26.7.0

In [14]:
import sys
import mysql.connector

print("Python:")
print(sys.executable)

print("\nConnector version:")
print(mysql.connector.__version__)

print("\nConnector location:")
print(mysql.connector.__file__)

Python:
c:\Users\RADHE\AppData\Local\Programs\Python\Python311\python.exe

Connector version:
26.7.0

Connector location:
c:\Users\RADHE\AppData\Local\Programs\Python\Python311\Lib\site-packages\mysql\connector\__init__.py

In [15]:
import sys

!{sys.executable} -m pip uninstall mysql-connector-python -y

Found existing installation: mysql-connector-python 26.7.0
Uninstalling mysql-connector-python-26.7.0:
  Successfully uninstalled mysql-connector-python-26.7.0

WARNING: Failed to remove contents in a temporary directory 'C:\Users\RADHE\AppData\Local\Temp\pip-uninstall-ktmiu1_5'.
You can safely remove it manually.

In [16]:
!{sys.executable} -m pip install --upgrade --force-reinstall mysql-connector-python

Collecting mysql-connector-python
  Using cached mysql_connector_python-26.7.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Using cached mysql_connector_python-26.7.0-cp311-cp311-win_amd64.whl (17.7 MB)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import mysql.connector

print(mysql.connector.__version__)

26.7.0

:

In [ ]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="#Rehan2003",
    database="customers"
)

print("Connected:", conn.is_connected())

SO in this way we have to connect to the database and then we can fetch the data from the database and then we can use the data for our analysis.