# Understanding Data

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('../DATASET/bollywood.csv')

## 1. How big is the data?

In [7]:
df.shape

(1500, 2)

## 2. How does the data look like?

In [8]:
df.head()

                                  movie              lead
0              Uri: The Surgical Strike     Vicky Kaushal
1                         Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister (film)       Anupam Kher
3                       Why Cheat India     Emraan Hashmi
4                       Evening Shadows  Mona Ambegaonkar

## 3. What are the data types of each column?

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   movie   1500 non-null   object
 1   lead    1500 non-null   object
dtypes: object(2)
memory usage: 23.6+ KB

## 4. Are there any missing values in the data?

In [10]:
df.isnull().sum()

movie    0
lead     0
dtype: int64

## 5. How does the data look mathematically?

In [11]:
df.describe()

                          movie          lead
count                      1500          1500
unique                     1497           566
top     Tanu Weds Manu: Returns  Akshay Kumar
freq                          2            48

## 6. Are there any missing values in the data?

In [12]:
df.duplicated().sum()

3

## 7. How is the correlation between the features?

In [14]:
#df.corr() 
## not for this dataset as it has categorical data. We can use other methods to find correlation between categorical data.

## 8. How is the distribution of the features?
## 9. How is the distribution of the target variable?
## 10. How is the distribution of the features with respect to the target variable?
## 11. How about the outliers in the data?